import type { Rating, IntentPreset } from "./types";

export interface OverrideEntry {
  photoHash: string;
  /** One-line gist of the frame, generated by a small model call at override time. */
  shortDescription: string;
  sessionIntent: IntentPreset;
  originalScore: number;
  originalRating: Rating;
  userRating: Rating;
  timestamp: number;
}

export interface OverrideStore {
  version: 1;
  entries: OverrideEntry[];
}

const STORAGE_KEY = "cs-overrides";
const MAX_ENTRIES = 30;

export const OVERRIDES_CHANGED_EVENT = "cs-overrides-changed";

export function emptyStore(): OverrideStore {
  return { version: 1, entries: [] };
}

/** Drop oldest entries past the cap. */
export function evictFifo(store: OverrideStore): OverrideStore {
  if (store.entries.length <= MAX_ENTRIES) return store;
  const sorted = [...store.entries].sort((a, b) => a.timestamp - b.timestamp);
  return { ...store, entries: sorted.slice(store.entries.length - MAX_ENTRIES) };
}

export function getOverridesClient(): OverrideStore {
  if (typeof window === "undefined") return emptyStore();
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return emptyStore();
  try {
    const parsed = JSON.parse(raw) as OverrideStore;
    if (parsed.version !== 1 || !Array.isArray(parsed.entries)) return emptyStore();
    return parsed;
  } catch {
    return emptyStore();
  }
}

export function setOverridesClient(store: OverrideStore): void {
  if (typeof window === "undefined") return;
  const next = evictFifo(store);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
  window.dispatchEvent(new CustomEvent(OVERRIDES_CHANGED_EVENT));
}

/**
 * Append a new override. If an entry already exists for this photoHash,
 * replace it with the latest user decision (most recent rating wins).
 */
export function recordOverride(entry: OverrideEntry): void {
  const current = getOverridesClient();
  const filtered = current.entries.filter((e) => e.photoHash !== entry.photoHash);
  setOverridesClient({ ...current, entries: [...filtered, entry] });
}

/**
 * Pick the most relevant overrides for a cull request, weighting by
 * matching sessionIntent. Returns up to `limit`, recency-sorted within
 * each tier (intent-match first, then others).
 */
export function selectFewShot(
  store: OverrideStore,
  sessionIntent: IntentPreset,
  limit: number,
): OverrideEntry[] {
  const matches = store.entries.filter((e) => e.sessionIntent === sessionIntent);
  const others = store.entries.filter((e) => e.sessionIntent !== sessionIntent);
  const byRecent = (a: OverrideEntry, b: OverrideEntry) => b.timestamp - a.timestamp;
  return [...matches.sort(byRecent), ...others.sort(byRecent)].slice(0, limit);
}
