import type { Rating, IntentPreset } from "./types";

export interface OverrideEntry {
  photoHash: string;
  /** One-line gist of the frame, generated by a small model call at override time. */
  shortDescription: string;
  sessionIntent: IntentPreset;
  originalScore: number;
  originalRating: Rating;
  userRating: Rating;
  timestamp: number;
  profileIdAtCull?: string | null;
}

export interface OverrideStore {
  version: 1;
  entries: OverrideEntry[];
}

const STORAGE_KEY = "cs-overrides";
const MAX_ENTRIES = 30;

export const OVERRIDES_CHANGED_EVENT = "cs-overrides-changed";

export function emptyStore(): OverrideStore {
  return { version: 1, entries: [] };
}

/** Drop oldest entries past the cap. */
export function evictFifo(store: OverrideStore): OverrideStore {
  if (store.entries.length <= MAX_ENTRIES) return store;
  const sorted = [...store.entries].sort((a, b) => a.timestamp - b.timestamp);
  return { ...store, entries: sorted.slice(store.entries.length - MAX_ENTRIES) };
}

export function getOverridesClient(): OverrideStore {
  if (typeof window === "undefined") return emptyStore();
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return emptyStore();
  try {
    const parsed = JSON.parse(raw) as OverrideStore;
    if (parsed.version !== 1 || !Array.isArray(parsed.entries)) return emptyStore();
    return parsed;
  } catch {
    return emptyStore();
  }
}

export function setOverridesClient(store: OverrideStore): void {
  if (typeof window === "undefined") return;
  const next = evictFifo(store);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
  window.dispatchEvent(new CustomEvent(OVERRIDES_CHANGED_EVENT));
}

/**
 * Append a new override. If an entry already exists for this photoHash,
 * replace it with the latest user decision (most recent rating wins).
 */
export function recordOverride(entry: OverrideEntry): void {
  const current = getOverridesClient();
  const filtered = current.entries.filter((e) => e.photoHash !== entry.photoHash);
  setOverridesClient({ ...current, entries: [...filtered, entry] });
}

export function removeOverride(photoHash: string): void {
  const current = getOverridesClient();
  const filtered = current.entries.filter((e) => e.photoHash !== photoHash);
  if (filtered.length === current.entries.length) return;
  setOverridesClient({ ...current, entries: filtered });
}

export function clearAllOverrides(): void {
  setOverridesClient(emptyStore());
}

export function correctionsForProfile(entries: OverrideEntry[], profileId: string | null | undefined): OverrideEntry[] {
  if (!profileId) return [];
  return entries.filter((entry) => entry.profileIdAtCull === profileId);
}

export function scopeUnscopedOverrides(store: OverrideStore, profileId: string): OverrideStore {
  return {
    ...store,
    entries: store.entries.map((entry) =>
      entry.profileIdAtCull === undefined ? { ...entry, profileIdAtCull: profileId } : entry
    ),
  };
}

export function scopeUnscopedOverridesClient(profileId: string): void {
  const current = getOverridesClient();
  const next = scopeUnscopedOverrides(current, profileId);
  if (JSON.stringify(next) !== JSON.stringify(current)) {
    setOverridesClient(next);
  }
}

const RATING_ORDER: Rating[] = ["CUT", "MAYBE", "SELECT", "HERO"];

/** +N if user pushed up, -N if user pushed down, 0 if same. */
export function bucketDelta(original: Rating, user: Rating): number {
  return RATING_ORDER.indexOf(user) - RATING_ORDER.indexOf(original);
}

export function signalPolarity(entry: OverrideEntry): "positive" | "negative" | "neutral" {
  const d = bucketDelta(entry.originalRating, entry.userRating);
  if (d > 0) return "positive";
  if (d < 0) return "negative";
  return "neutral";
}
